// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_sync_manual from "./routes/api/sync/manual.ts";
import * as $index from "./routes/index.tsx";
import * as $orders_index from "./routes/orders/index.tsx";
import * as $sync_index from "./routes/sync/index.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/sync/manual.ts": $api_sync_manual,
    "./routes/index.tsx": $index,
    "./routes/orders/index.tsx": $orders_index,
    "./routes/sync/index.tsx": $sync_index,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;